const deck = [
  {
    number: "Ace",
    rank: 14,
    suit: "Clubs",
    imageURL: "ace_of_clubs.png",
    altText: "Ace of Clubs",
  },
  {
    number: "2",
    rank: 2,
    suit: "Clubs",
    imageURL: "2_of_clubs.png",
    altText: "2 of Clubs",
  },
  {
    number: "3",
    rank: 3,
    suit: "Clubs",
    imageURL: "3_of_clubs.png",
    altText: "3 of Clubs",
  },
  {
    number: "4",
    rank: 4,
    suit: "Clubs",
    imageURL: "4_of_clubs.png",
    altText: "4 of Clubs",
  },
  {
    number: "5",
    rank: 5,
    suit: "Clubs",
    imageURL: "5_of_clubs.png",
    altText: "5 of Clubs",
  },
  {
    number: "6",
    rank: 6,
    suit: "Clubs",
    imageURL: "6_of_clubs.png",
    altText: "6 of Clubs",
  },
  {
    number: "7",
    rank: 7,
    suit: "Clubs",
    imageURL: "7_of_clubs.png",
    altText: "7 of Clubs",
  },
  {
    number: "8",
    rank: 8,
    suit: "Clubs",
    imageURL: "8_of_clubs.png",
    altText: "8 of Clubs",
  },
  {
    number: "9",
    rank: 9,
    suit: "Clubs",
    imageURL: "9_of_clubs.png",
    altText: "9 of Clubs",
  },
  {
    number: "10",
    rank: 10,
    suit: "Clubs",
    imageURL: "10_of_clubs.png",
    altText: "10 of Clubs",
  },
  {
    number: "Jack",
    rank: 11,
    suit: "Clubs",
    imageURL: "jack_of_clubs.png",
    altText: "Jack of Clubs",
  },
  {
    number: "Queen",
    rank: 12,
    suit: "Clubs",
    imageURL: "queen_of_clubs.png",
    altText: "Queen of Clubs",
  },
  {
    number: "King",
    rank: 13,
    suit: "Clubs",
    imageURL: "king_of_clubs.png",
    altText: "King of Clubs",
  },
  {
    number: "Ace",
    rank: 14,
    suit: "Diamonds",
    imageURL: "ace_of_diamonds.png",
    altText: "Ace of Diamonds",
  },
  {
    number: "2",
    rank: 2,
    suit: "Diamonds",
    imageURL: "2_of_diamonds.png",
    altText: "2 of Diamonds",
  },
  {
    number: "3",
    rank: 3,
    suit: "Diamonds",
    imageURL: "3_of_diamonds.png",
    altText: "3 of Diamonds",
  },
  {
    number: "4",
    rank: 4,
    suit: "Diamonds",
    imageURL: "4_of_diamonds.png",
    altText: "4 of Diamonds",
  },
  {
    number: "5",
    rank: 5,
    suit: "Diamonds",
    imageURL: "5_of_diamonds.png",
    altText: "5 of Diamonds",
  },
  {
    number: "6",
    rank: 6,
    suit: "Diamonds",
    imageURL: "6_of_diamonds.png",
    altText: "6 of Diamonds",
  },
  {
    number: "7",
    rank: 7,
    suit: "Diamonds",
    imageURL: "7_of_diamonds.png",
    altText: "7 of Diamonds",
  },
  {
    number: "8",
    rank: 8,
    suit: "Diamonds",
    imageURL: "8_of_diamonds.png",
    altText: "8 of Diamonds",
  },
  {
    number: "9",
    rank: 9,
    suit: "Diamonds",
    imageURL: "9_of_diamonds.png",
    altText: "9 of Diamonds",
  },
  {
    number: "10",
    rank: 10,
    suit: "Diamonds",
    imageURL: "10_of_diamonds.png",
    altText: "10 of Diamonds",
  },
  {
    number: "Jack",
    rank: 11,
    suit: "Diamonds",
    imageURL: "jack_of_diamonds.png",
    altText: "Jack of Diamonds",
  },
  {
    number: "Queen",
    rank: 12,
    suit: "Diamonds",
    imageURL: "queen_of_diamonds.png",
    altText: "Queen of Diamonds",
  },
  {
    number: "King",
    rank: 13,
    suit: "Diamonds",
    imageURL: "king_of_diamonds.png",
    altText: "King of Diamonds",
  },
  {
    number: "Ace",
    rank: 14,
    suit: "Hearts",
    imageURL: "ace_of_hearts.png",
    altText: "Ace of Hearts",
  },
  {
    number: "2",
    rank: 2,
    suit: "Hearts",
    imageURL: "2_of_hearts.png",
    altText: "2 of Hearts",
  },
  {
    number: "3",
    rank: 3,
    suit: "Hearts",
    imageURL: "3_of_hearts.png",
    altText: "3 of Hearts",
  },
  {
    number: "4",
    rank: 4,
    suit: "Hearts",
    imageURL: "4_of_hearts.png",
    altText: "4 of Hearts",
  },
  {
    number: "5",
    rank: 5,
    suit: "Hearts",
    imageURL: "5_of_hearts.png",
    altText: "5 of Hearts",
  },
  {
    number: "6",
    rank: 6,
    suit: "Hearts",
    imageURL: "6_of_hearts.png",
    altText: "6 of Hearts",
  },
  {
    number: "7",
    rank: 7,
    suit: "Hearts",
    imageURL: "7_of_hearts.png",
    altText: "7 of Hearts",
  },
  {
    number: "8",
    rank: 8,
    suit: "Hearts",
    imageURL: "8_of_hearts.png",
    altText: "8 of Hearts",
  },
  {
    number: "9",
    rank: 9,
    suit: "Hearts",
    imageURL: "9_of_hearts.png",
    altText: "9 of Hearts",
  },
  {
    number: "10",
    rank: 10,
    suit: "Hearts",
    imageURL: "10_of_hearts.png",
    altText: "10 of Hearts",
  },
  {
    number: "Jack",
    rank: 11,
    suit: "Hearts",
    imageURL: "jack_of_hearts.png",
    altText: "Jack of Hearts",
  },
  {
    number: "Queen",
    rank: 12,
    suit: "Hearts",
    imageURL: "queen_of_hearts.png",
    altText: "Queen of Hearts",
  },
  {
    number: "King",
    rank: 13,
    suit: "Hearts",
    imageURL: "king_of_hearts.png",
    altText: "King of Hearts",
  },
  {
    number: "Ace",
    rank: 14,
    suit: "Spades",
    imageURL: "ace_of_spades.png",
    altText: "Ace of Spades",
  },
  {
    number: "2",
    rank: 2,
    suit: "Spades",
    imageURL: "2_of_spades.png",
    altText: "2 of Spades",
  },
  {
    number: "3",
    rank: 3,
    suit: "Spades",
    imageURL: "3_of_spades.png",
    altText: "3 of Spades",
  },
  {
    number: "4",
    rank: 4,
    suit: "Spades",
    imageURL: "4_of_spades.png",
    altText: "4 of Spades",
  },
  {
    number: "5",
    rank: 5,
    suit: "Spades",
    imageURL: "5_of_spades.png",
    altText: "5 of Spades",
  },
  {
    number: "6",
    rank: 6,
    suit: "Spades",
    imageURL: "6_of_spades.png",
    altText: "6 of Spades",
  },
  {
    number: "7",
    rank: 7,
    suit: "Spades",
    imageURL: "7_of_spades.png",
    altText: "7 of Spades",
  },
  {
    number: "8",
    rank: 8,
    suit: "Spades",
    imageURL: "8_of_spades.png",
    altText: "8 of Spades",
  },
  {
    number: "9",
    rank: 9,
    suit: "Spades",
    imageURL: "9_of_spades.png",
    altText: "9 of Spades",
  },
  {
    number: "10",
    rank: 10,
    suit: "Spades",
    imageURL: "10_of_spades.png",
    altText: "10 of Spades",
  },
  {
    number: "Jack",
    rank: 11,
    suit: "Spades",
    imageURL: "jack_of_spades.png",
    altText: "Jack of Spades",
  },
  {
    number: "Queen",
    rank: 12,
    suit: "Spades",
    imageURL: "queen_of_spades.png",
    altText: "Queen of Spades",
  },
  {
    number: "King",
    rank: 13,
    suit: "Spades",
    imageURL: "king_of_spades.png",
    altText: "King of Spades",
  },
];

export { deck };
